import "@/styles/globals.css";
// import SideBar from "@/app/_components/organisims/side-bar";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "@/trpc/react";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="h-screen">
        <TRPCReactProvider>
        {children}
    </TRPCReactProvider>
      </body>
    </html>
  );
}
